// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const QCC_TRUE = 0x1;
const QCC_FALSE = 0x0;
const ALLJOYN_MESSAGE_FLAG_NO_REPLY_EXPECTED = 0x1;
const ALLJOYN_MESSAGE_FLAG_AUTO_START = 0x2;
const ALLJOYN_MESSAGE_FLAG_ALLOW_REMOTE_MSG = 0x4;
const ALLJOYN_MESSAGE_FLAG_SESSIONLESS = 0x10;
const ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST = 0x20;
const ALLJOYN_MESSAGE_FLAG_ENCRYPTED = 0x80;
const ALLJOYN_TRAFFIC_TYPE_MESSAGES = 0x1;
const ALLJOYN_TRAFFIC_TYPE_RAW_UNRELIABLE = 0x2;
const ALLJOYN_TRAFFIC_TYPE_RAW_RELIABLE = 0x4;
const ALLJOYN_PROXIMITY_ANY = 0xff;
const ALLJOYN_PROXIMITY_PHYSICAL = 0x1;
const ALLJOYN_PROXIMITY_NETWORK = 0x2;
const ALLJOYN_READ_READY = 0x1;
const ALLJOYN_WRITE_READY = 0x2;
const ALLJOYN_DISCONNECTED = 0x4;
const ALLJOYN_LITTLE_ENDIAN = 0x242016c;
const ALLJOYN_BIG_ENDIAN = 0x10010242;
const ALLJOYN_MESSAGE_DEFAULT_TIMEOUT = 0x61a8;
const ALLJOYN_CRED_PASSWORD = 0x2020001;
const ALLJOYN_CRED_USER_NAME = 0x4020002;
const ALLJOYN_CRED_CERT_CHAIN = 0x20004;
const ALLJOYN_CRED_PRIVATE_KEY = 0x9020008;
const ALLJOYN_CRED_LOGON_ENTRY = 0x5020010;
const ALLJOYN_CRED_EXPIRATION = 0x40020020;
const ALLJOYN_CRED_NEW_PASSWORD = 0x1021001;
const ALLJOYN_CRED_ONE_TIME_PWD = 0x1012001;
const ALLJOYN_PROP_ACCESS_READ = 0x1020101;
const ALLJOYN_PROP_ACCESS_WRITE = 0x1030102;
const ALLJOYN_PROP_ACCESS_RW = 0x1040103;
const ALLJOYN_MEMBER_ANNOTATE_NO_REPLY = 0x1020101;
const ALLJOYN_MEMBER_ANNOTATE_DEPRECATED = 0x1030102;
const ALLJOYN_MEMBER_ANNOTATE_SESSIONCAST = 0x1080104;
const ALLJOYN_MEMBER_ANNOTATE_SESSIONLESS = 0x1100108;
const ALLJOYN_MEMBER_ANNOTATE_UNICAST = 0x4200110;
const ALLJOYN_MEMBER_ANNOTATE_GLOBAL_BROADCAST = 0x80010420;
