// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const WINTRUST_MAX_HEADER_BYTES_TO_MAP_DEFAULT = 0xa00000;
const WINTRUST_MAX_HASH_BYTES_TO_MAP_DEFAULT = 0x100000;
const WSS_VERIFY_SEALING = 0x4;
const WSS_INPUT_FLAG_MASK = 0x7;
const WSS_OUT_SEALING_STATUS_VERIFIED = 0x80000000;
const WSS_OUT_HAS_SEALING_INTENT = 0x40000000;
const WSS_OUT_FILE_SUPPORTS_SEAL = 0x20000000;
const WSS_OUTPUT_FLAG_MASK = 0xe0000000;
const TRUSTERROR_STEP_WVTPARAMS = 0x0;
const TRUSTERROR_STEP_FILEIO = 0x2;
const TRUSTERROR_STEP_SIP = 0x3;
const TRUSTERROR_STEP_SIPSUBJINFO = 0x5;
const TRUSTERROR_STEP_CATALOGFILE = 0x6;
const TRUSTERROR_STEP_CERTSTORE = 0x7;
const TRUSTERROR_STEP_MESSAGE = 0x8;
const TRUSTERROR_STEP_MSG_SIGNERCOUNT = 0x9;
const TRUSTERROR_STEP_MSG_INNERCNTTYPE = 0xa;
const TRUSTERROR_STEP_MSG_INNERCNT = 0xb;
const TRUSTERROR_STEP_MSG_STORE = 0xc;
const TRUSTERROR_STEP_MSG_SIGNERINFO = 0xd;
const TRUSTERROR_STEP_MSG_SIGNERCERT = 0xe;
const TRUSTERROR_STEP_MSG_CERTCHAIN = 0xf;
const TRUSTERROR_STEP_MSG_COUNTERSIGINFO = 0x10;
const TRUSTERROR_STEP_MSG_COUNTERSIGCERT = 0x11;
const TRUSTERROR_STEP_VERIFY_MSGHASH = 0x12;
const TRUSTERROR_STEP_VERIFY_MSGINDIRECTDATA = 0x13;
const TRUSTERROR_STEP_FINAL_WVTINIT = 0x1e;
const TRUSTERROR_STEP_FINAL_INITPROV = 0x1f;
const TRUSTERROR_STEP_FINAL_OBJPROV = 0x20;
const TRUSTERROR_STEP_FINAL_SIGPROV = 0x21;
const TRUSTERROR_STEP_FINAL_CERTPROV = 0x22;
const TRUSTERROR_STEP_FINAL_CERTCHKPROV = 0x23;
const TRUSTERROR_STEP_FINAL_POLICYPROV = 0x24;
const TRUSTERROR_STEP_FINAL_UIPROV = 0x25;
const TRUSTERROR_MAX_STEPS = 0x26;
const WSS_OBJTRUST_SUPPORT = 0x1;
const WSS_SIGTRUST_SUPPORT = 0x2;
const WSS_CERTTRUST_SUPPORT = 0x4;
const WT_CURRENT_VERSION = 0x200;
const WT_ADD_ACTION_ID_RET_RESULT_FLAG = 0x1;
const SPC_UUID_LENGTH = 0x10;
const WIN_CERT_REVISION_1_0 = 0x100;
const WIN_CERT_REVISION_2_0 = 0x200;
const WIN_CERT_TYPE_X509 = 0x1;
const WIN_CERT_TYPE_PKCS_SIGNED_DATA = 0x2;
const WIN_CERT_TYPE_RESERVED_1 = 0x3;
const WIN_CERT_TYPE_TS_STACK_SIGNED = 0x4;
const WT_TRUSTDBDIALOG_NO_UI_FLAG = 0x1;
const WT_TRUSTDBDIALOG_ONLY_PUB_TAB_FLAG = 0x2;
const WT_TRUSTDBDIALOG_WRITE_LEGACY_REG_FLAG = 0x100;
const WT_TRUSTDBDIALOG_WRITE_IEAK_STORE_FLAG = 0x200;
